### ISSUE TITLE
Multiple Children - Associate child id with order items

### ISSUE THREAD

**Issue by fadyham** [saraguirgis/beelish#22]
**Functions file:**
DONE - Update meal in cart to be based on child id
- Update meal already bought function

**Order page template:**
DONE - Populate drop down with child(ren)'s name(s)

**Product page:**
DONE - Display child name & class
DONE - Add child id attribute to item in cart

**Cart page:**
DONE - Display child name & class
DONE - Add Child Name and Class Name as metadata to order item (not child ID so that order history would show what was actually ordered at that time)

**My account > View Order:**
DONE - (non-MVP) Display order item metadata (Child Name & class name)

**Confirmation Email:**
DONE - Add child name & class to order confirmation email

**Comment by saraguirgis** [comment]
TO DO:
- comment out the code that makes the calendar view display "View Details" instead of "order" if the product was previously purchased
- comment out the code that removes the add to cart button if the product was previously purchased
- write function to 1. show all items ordered matching sku or ID and then 2. compare first and last name for ordered item
- function to return the metadata (childname) of all ordered products with a given sku
- display child name(s) if purchased
